LFS_PKGS_NAME_LIST= \
    man-pages       \
    iana-etc        \
    glibc           \
    zlib            \
    bzip2           \
    xz              \
    zstd            \
    file            \
    readline        \
    m4              \
    bc              \
    flex            \
    tcl             \
    expect          \
    dejagnu         \
    binutils        \
    gmp             \
    mpfr            \
    mpc             \
    attr            \
    acl             \
    libcap          \
    shadow          \
    gcc             \
    pkg-config      \
    ncurses         \
    sed             \
    psmisc          \
    gettext         \
    bison           \
    grep            \
    bash            \
    libtool         \
    gdbm            \
    gperf           \
    expat           \
    inetutils       \
    less            \
    perl            \
    xml             \
    intltool        \
    autoconf        \
    automake        \
    openssl         \
    kmod            \
    libelf          \
    libffi          \
    python          \
    wheel           \
    ninja           \
    meson           \
    coreutils       \
    check           \
    diffutils       \
    gawk            \
    findutils       \
    groff           \
    grub            \
    gzip            \
    iproute         \
    kbd             \
    libpipeline     \
    make            \
    patch           \
    tar             \
    texinfo         \
    vim             \
    markupsafe      \
    jinja           \
    systemd         \
    dbus            \
    man-db          \
    procps-ng       \
    util-linux      \
    e2fsprogs